export enum LEAD_POSITION {
  CAPTACAO = 'CAPTACAO',
  PRIMEIRO_PAGAMENTO = 'PRIMEIRO_PAGAMENTO',
  ENVIO_DOCUMENTOS = 'ENVIO_DOCUMENTOS',
  VALIDACAO_DOCUMENTOS = 'VALIDACAO_DOCUMENTOS',
  SELECAO_IMOVEL = 'SELECAO_IMOVEL',
  PAGAMENTO_IMOVEL = 'PAGAMENTO_IMOVEL',
  ASSINATURA_CONTRATO = 'ASSINATURA_CONTRATO',
  PREPARACAO_IMOVEL = 'PREPARACAO_IMOVEL',
  SERVICOS_ADICIONAIS = 'SERVICOS_ADICIONAIS',
  ENTREGA_IMOVEL = 'ENTREGA_IMOVEL',
  PENDENCIA = 'PENDENCIA',
  CANCELADO = 'CANCELADO',
}
